name: build_and_push

on:
  pull_request:
  push:
    branches: [master]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

  build_docker:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image and save it to a file
        run: |
          DOCKER_REPO=vivareal make docker_image
          mkdir -p /tmp/docker-cache
          docker save -o /tmp/docker-cache/x9.tar ${{ secrets.CONTAINER_REGISTRY_HOST }}/vivareal/observability/x9:latest
      - name: Cache Docker image for further jobs in this workflow run
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-cache
          path: /tmp/docker-cache/
          retention-days: 1

  push_master_docker:
    if: github.ref == 'refs/heads/master'
    name: Push Docker image with tag master
    needs: build_docker
    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: vivareal
      DOCKER_IMAGE_VERSION: master
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download cached Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-image-cache
          path: /tmp/docker-cache/
      - name: Load Docker image and tag it as master
        run: |
          docker load < /tmp/docker-cache/x9.tar
          make docker_tag
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Docker image with tag master
        run: make docker_push

  push_release_docker:
    if: "startsWith(github.ref, 'refs/tags/v')"
    name: Push Docker image according to release
    needs: build_docker
    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: vivareal
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download cached Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-image-cache
          path: /tmp/docker-cache/
      - name: Load Docker image and tag it according to current release
        run: |
          docker load < /tmp/docker-cache/x9.tar
          make docker_tag DOCKER_IMAGE_VERSION=${GITHUB_REF#refs/tags/}
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Docker image with release tag
        run: make docker_push DOCKER_IMAGE_VERSION=${GITHUB_REF#refs/tags/}
      - name: Push Docker image with latest tag if this version is stable
        run: |
          if [[ "${{ github.ref }}" =~ "^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$" ]]; then
            make docker_push DOCKER_IMAGE_VERSION=latest
          fi

